# Generated by Django 5.2.3 on 2025-06-27 04:39

from django.db import migrations
import uuid

def seed_accounts(apps, schema_editor):
    Account = apps.get_model('accounts', 'Account')
    accounts = [
        ("Mpesa_KES_1", "KES"),
        ("Mpesa_KES_2", "KES"),
        ("Bank_KES_3", "KES"),
        ("Bank_USD_1", "USD"),
        ("Bank_USD_2", "USD"),
        ("Bank_USD_3", "USD"),
        ("Wallet_NGN_1", "NGN"),
        ("Wallet_NGN_2", "NGN"),
        ("Mobile_NGN_3", "NGN"),
        ("Reserve_KES_4", "KES"),
    ]

    for name, currency in accounts:
        Account.objects.create(
            account_id=uuid.uuid4(),
            account_name=name,
            currency=currency,
            balance=100000.00  # or any default value
        )

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
         migrations.RunPython(seed_accounts),
    ]
