# Generated by Django 5.2.3 on 2025-06-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
